### ISSUE TITLE
Test #37

### ISSUE THREAD

**Issue by lemonjuiceexe** [lemonjuiceexe/Chess#38]
Test whether the issue that I described in #37 discussion actually occurs.

**Comment by Bruhtek** [comment]
It doesn't, and if it does then it would occur in previous version as well, since:

- It's invoked in Start() method
- We just replaced `switch (...) case -35f` (still checking for full number) with a `transform.position.x + 5 % 10 != 0`, so nothing really changed that much

Closing, if the issue were to actually occur we can reopen this
