### ISSUE TITLE
Bugs with moving

### ISSUE THREAD

**Issue by lemonjuiceexe** [lemonjuiceexe/Chess#8]
There are some bugs with moving - you cannot always select a piece.

**Comment by Bruhtek** [comment]
To add to it:
1. It only happens with certain pieces (the same each time the game is run)
2. It's avoided entirely if the piece is selected first (? maybe, need some more testing)
3. Expanding on 2, it seems to be able to sometimes be fixed by moving pieces around it
4. **It's probably cased by clicking pieces around it**, since it doesn't happen when moving pieces on the other side of the board
5. It **propably** doesn't happen when piece was already moved (requires more testing)

**Comment by lemonjuiceexe** [comment]
Overall: ???

**Comment by lemonjuiceexe** [comment]
Sometimes when bugged piece is actually selectable, when it takes, it does not delete the piece it takes. All of these issues are kinda hard to reproduce, so it's hard to say if this is connected to mobing issues.

**Comment by lemonjuiceexe** [comment]
When piece is bugged, it also can't be taken - piece taking goes under it.

Most often bugged are black knight and rook (Queenside).
Best way to recreate the bug, is to click at every piece before the first move

**Comment by lemonjuiceexe** [comment]
![image](https://user-images.githubusercontent.com/74901431/104095430-086f8e00-5297-11eb-8dee-82ec79819f27.png)
